const projects = window.PROJECTS;
const list = document.querySelector('#projects');
projects.forEach((p,i)=>{const b=document.createElement('button');b.className='project';b.dataset.cursor='VIEW PROJECT';b.setAttribute('aria-label','View project: '+p.title);b.innerHTML=`<span class="project-image"><img src="${p.thumbnail}" alt="" loading="lazy" width="320" height="180"><span class="project-number">0${i+1}</span><span class="project-action">View project ↗</span></span><span class="project-info"><span><h3>${p.title}</h3><p>${p.client} / Long-form / Video editing</p></span><span>↗</span></span>`;list.append(b)});
const reduced=matchMedia('(prefers-reduced-motion: reduce)'),fine=matchMedia('(hover: hover) and (pointer: fine)');
const dialog=document.querySelector('dialog'),player=document.querySelector('#player');let opener;
function openProject(p,button){opener=button;document.querySelector('#project-title').textContent=p.title;document.querySelector('#project-client').textContent=p.client+' / VIDEO EDITING';document.querySelector('#project-description').textContent=p.description||'Long-form video editing for '+p.client+'.';document.querySelector('#youtube-link').href=p.url;player.replaceChildren();const img=new Image();img.src=p.thumbnail;img.alt=p.title;player.append(img);const play=document.createElement('button');play.className='play-large';play.dataset.cursor='PLAY';play.textContent='▶ PLAY';play.setAttribute('aria-label','Play '+p.title);play.onclick=()=>{const frame=document.createElement('iframe');frame.title=p.title;frame.src=`https://www.youtube-nocookie.com/embed/${p.id}?autoplay=1&rel=0`;frame.allow='autoplay; encrypted-media; picture-in-picture; fullscreen';frame.allowFullscreen=true;player.replaceChildren(frame);hideCursor();};player.append(play);dialog.append(cursor,dot);dialog.showModal();document.body.style.overflow='hidden';hideCursor();}
list.querySelectorAll('.project').forEach((b,i)=>b.addEventListener('click',()=>openProject(projects[i],b)));
document.querySelector('#close').onclick=()=>dialog.close();dialog.addEventListener('close',()=>{player.replaceChildren();document.body.append(cursor,dot);document.body.style.overflow='';opener?.focus({preventScroll:true});hideCursor()});
document.querySelector('#year').textContent=new Date().getFullYear();
const cursor=document.querySelector('#cursor'),dot=document.querySelector('#dot'),light=document.querySelector('#light');let x=0,y=0,cx=0,cy=0,lx=0,ly=0,active=false,raf=0,last=0,magnet=null,tilt=null;
function hideCursor(){active=false;cursor.classList.add('hidden');dot.classList.add('hidden');}
function resetTargets(){if(magnet)magnet.style.transform='';if(tilt){tilt.style.setProperty('--rx','0deg');tilt.style.setProperty('--ry','0deg')}magnet=null;tilt=null;}
function configure(){const enabled=fine.matches&&!reduced.matches;document.body.classList.toggle('cursor-enabled',enabled);document.body.classList.toggle('motion',!reduced.matches);if(!enabled){hideCursor();resetTargets();cancelAnimationFrame(raf);raf=0} }
function animate(t){raf=0;if(!active||document.hidden)return;const dt=Math.min(t-last||16.7,50);last=t;const a=1-Math.exp(-dt/35);cx+=(x-cx)*a;cy+=(y-cy)*a;lx+=(x-lx)*(1-Math.exp(-dt/110));ly+=(y-ly)*(1-Math.exp(-dt/110));cursor.style.transform=`translate3d(${cx}px,${cy}px,0)`;light.style.transform=`translate3d(${lx-275}px,${ly-275}px,0)`;if(Math.abs(x-cx)+Math.abs(y-cy)+Math.abs(x-lx)+Math.abs(y-ly)>.15)raf=requestAnimationFrame(animate);}
document.addEventListener('pointermove',e=>{if(!fine.matches||reduced.matches||e.pointerType==='touch')return;x=e.clientX;y=e.clientY;if(!active){cx=lx=x;cy=ly=y;active=true;cursor.classList.remove('hidden');dot.classList.remove('hidden')}dot.style.transform=`translate3d(${x-2}px,${y-2}px,0)`;const target=e.target.closest('[data-cursor],a,button');cursor.classList.toggle('active',!!target?.dataset.cursor);cursor.classList.toggle('link',!!target&&!target.dataset.cursor);cursor.firstElementChild.textContent=target?.dataset.cursor||'';const m=e.target.closest('.magnetic');if(m!==magnet){if(magnet)magnet.style.transform='';magnet=m}if(magnet){const r=magnet.getBoundingClientRect();magnet.style.transform=`translate3d(${(x-r.left-r.width/2)*.12}px,${(y-r.top-r.height/2)*.17}px,0)`}const v=e.target.closest('.project')?.querySelector('.project-image');if(v!==tilt){if(tilt){tilt.style.setProperty('--rx','0deg');tilt.style.setProperty('--ry','0deg')}tilt=v}if(tilt){const r=tilt.getBoundingClientRect();tilt.style.setProperty('--rx',`${-(y-r.top-r.height/2)/r.height*1.6}deg`);tilt.style.setProperty('--ry',`${(x-r.left-r.width/2)/r.width*1.6}deg`)}if(!raf)raf=requestAnimationFrame(animate)},{passive:true});
document.documentElement.addEventListener('pointerleave',()=>{hideCursor();resetTargets()});window.addEventListener('blur',()=>{hideCursor();resetTargets()});document.addEventListener('visibilitychange',()=>{if(document.hidden){hideCursor();cancelAnimationFrame(raf);raf=0}});document.addEventListener('pointerdown',()=>cursor.classList.add('pressed'));document.addEventListener('pointerup',()=>cursor.classList.remove('pressed'));document.addEventListener('pointerover',e=>{if(e.target.tagName==='IFRAME')hideCursor()});document.addEventListener('keydown',e=>{if(e.key==='Tab')hideCursor()});fine.addEventListener('change',configure);reduced.addEventListener('change',configure);configure();hideCursor();
const observer=new IntersectionObserver(entries=>entries.forEach(e=>{if(e.isIntersecting){e.target.classList.add('visible');e.target.querySelectorAll('.reveal-title').forEach(t=>t.classList.add('visible'));observer.unobserve(e.target)}}),{threshold:.08});document.querySelectorAll('.project').forEach(el=>observer.observe(el));document.querySelectorAll('.reveal-title').forEach(el=>observer.observe(el.parentElement));
let scrollPending=false;const strip=document.querySelector('.hero-content');function scrollFrame(){scrollPending=false;}window.addEventListener('scroll',()=>{resetTargets();if(!scrollPending){scrollPending=true;requestAnimationFrame(scrollFrame)}},{passive:true});

const featureControls=document.querySelector('.feature-controls');let featured=1;
function setFeatured(index){featured=index;const p=projects[index];document.querySelector('#hero-art-image').src=p.thumbnail;document.querySelector('#feature-image').src=p.thumbnail;document.querySelector('#feature-title').textContent=p.title;document.querySelector('#feature-client').textContent=p.client.toUpperCase()+' / LONG-FORM';document.querySelector('#feature-count').textContent=String(index+1).padStart(2,'0')+' / 06';document.querySelector('#hero-play').setAttribute('aria-label','Watch '+p.title);featureControls.querySelectorAll('button').forEach((b,i)=>b.setAttribute('aria-pressed',String(i===index)));if(!reduced.matches){document.querySelector('#feature-title').animate([{opacity:0,transform:'translateY(8px)'},{opacity:1,transform:'translateY(0)'}],{duration:400,easing:'cubic-bezier(.22,1,.36,1)'});document.querySelector('#hero-art-image').animate([{opacity:.25,transform:'scale(1.09)'},{opacity:.58,transform:'scale(1.06)'}],{duration:750,easing:'cubic-bezier(.22,1,.36,1)'})}}
projects.forEach((p,i)=>{const b=document.createElement('button');b.setAttribute('aria-label','Feature '+p.title);b.setAttribute('aria-pressed',String(i===1));b.onclick=()=>setFeatured(i);featureControls.append(b)});document.querySelector('#hero-play').onclick=e=>openProject(projects[featured],e.currentTarget);


const contactDialog=document.querySelector('#contact');let contactOpener;
document.querySelectorAll('[data-contact]').forEach(a=>a.addEventListener('click',e=>{e.preventDefault();contactOpener=a;contactDialog.append(cursor,dot);contactDialog.showModal();document.body.style.overflow='hidden';hideCursor()}));
document.querySelector('.contact-close').onclick=()=>contactDialog.close();contactDialog.addEventListener('click',e=>{if(e.target===contactDialog){const r=contactDialog.getBoundingClientRect();if(e.clientX<r.left||e.clientX>r.right||e.clientY<r.top||e.clientY>r.bottom)contactDialog.close()}});contactDialog.addEventListener('close',()=>{document.body.append(cursor,dot);document.body.style.overflow='';contactOpener?.focus({preventScroll:true});hideCursor()});
document.querySelector('#copy-discord').onclick=async()=>{const status=document.querySelector('#contact-feedback');try{await navigator.clipboard.writeText('.aquababy');status.textContent='Copied! Paste .aquababy into Add Friend on Discord.';document.querySelector('#copy-discord').textContent='Copied ✓'}catch{status.textContent='Select and copy this username: .aquababy';const range=document.createRange();range.selectNodeContents(document.querySelector('.discord-option small'));const selection=window.getSelection();selection.removeAllRanges();selection.addRange(range)}};
